import type { HeartbeatSnapshot } from "../types.js";

// Shape of a row to INSERT into the heartbeats table.
// id and created_at are omitted — generated by Supabase defaults.
export type HeartbeatInsert = {
  agent_id: string;
  session_key: string;
  task_summary: string | null;
  current_goal: string | null;
  progress_pct: number | null;
  decisions_so_far: unknown[];
  artifacts_so_far: unknown[];
  blockers: unknown[];
  context_hash: string | null;
  tokens_in: number;
  tokens_out: number;
  estimated_usd: number;
  is_alive: boolean;
};

export function buildHeartbeatInsert(params: {
  agentId: string;
  sessionKey: string;
  snapshot?: HeartbeatSnapshot;
  isAlive?: boolean;
}): HeartbeatInsert {
  const s = params.snapshot ?? {};
  return {
    agent_id: params.agentId,
    session_key: params.sessionKey,
    task_summary: s.task_summary ?? null,
    current_goal: s.current_goal ?? null,
    progress_pct: s.progress_pct ?? null,
    decisions_so_far: s.decisions_so_far ?? [],
    artifacts_so_far: s.artifacts_so_far ?? [],
    blockers: s.blockers ?? [],
    context_hash: s.context_hash ?? null,
    tokens_in: s.tokens_in ?? 0,
    tokens_out: s.tokens_out ?? 0,
    estimated_usd: s.estimated_usd ?? 0,
    is_alive: params.isAlive ?? true,
  };
}
